### PR TITLE
Added option to return `cs` of feature that fails filter.

### PR DESCRIPTION
**Pull request by khdusenbury**
Have not implemented in RecA tests, but wanted to get this pushed as it may help Allie figure out what's going on with one of her libraries that keeps failing the spacer filters.

### CODE REVIEW

**Comment by jbloom** [comment]
@khdusenbury: Before I look at this in more detail, can you merge #39 into `master` and then into this branch. That way the tests will automatically run for this, and then I will take a look at it.

**Comment by khdusenbury** [comment]
Okay, I think it's ready for review. If you have better ideas for fixing the `flake8` errors I fixed in my last commit, feel free to implement them!

**Comment by khdusenbury** [comment]
Definitely meant to also change `align_and_parse`, so re-ran the notebook and added that then re-requested review. Thanks!

**Comment by jbloom** [comment]
@khdusenbury: Looks good, I just merged it.

**Comment by jbloom** [comment]
@khdusenbury: Does this close issue #36? If so, I'll let you close that issue.

**Pull request merged**
