### PR TITLE
Merge consecutive deletions

### PR DESCRIPTION
**Pull request by Bernadetadad**
@jbloom this adds merge_dels. flake8 passed. 

One thing I'm not 100% sure is correct, is it okay that my function uses `import alignparse.consensus`? it's a bit strange to call `alignparse` within `alignparse`.

### CODE REVIEW

**Comment by khdusenbury** [comment]
I didn't do a thorough review (I'll leave that for Jesse), but this came through my email and I'm sort of curious when this is necessary? I would have thought the cs tags are designed that consecutive deletions would already be merged.

**Comment by jbloom** [comment]
@khdusenbury, this is for downstream analysis of libraries made from circularized viral genes that are then being de-circularized. If a deletion occurs at the circularization boundary, it will be split. 

> I didn't do a thorough review (I'll leave that for Jesse), but this came through my email and I'm sort of curious when this is necessary? I would have thought the cs tags are designed that consecutive deletions would already be merged.

**Review by jbloom — CHANGES_REQUESTED** [review]
@Bernadetadad, mostly looks good, but a few suggested changes:

1. Your function calls the return value of `process_mut_str` the variable `df`, which is standardly used to refer to data frames. Although you can technically call a variable whatever you want, code readability is greatly improved by using meaningful variable names (see [here](https://towardsdatascience.com/data-scientists-your-variable-names-are-awful-heres-how-to-fix-them-89053d2855be)). The [process_mut_str](https://jbloomlab.github.io/alignparse/alignparse.consensus.html#alignparse.consensus.process_mut_str) return a 3-tuple `(substitutions, deletions, insertions)`. So it would be much better to say: `_, deletions, _ = alignparse.consensus.process_mut_str(s)`.

2. In the loop over the deletions, it would again be good to use meaningful variable names (see link above). So rather than `i` looping over the deletions, how about `del` or `deletion`?

3. I don't really understand lines 154 to 157. Don't the elements in the deletion list always consist of just a single deletion? So why do you have a split on a string that never has a space? Also, you should use a regex that checks that your entire string matches what you want. I think this could be:
```
for deletion in deletions:
    mut_sites = re.fullmatch('del(?P<start>\-?\d+ )to(?P<end>\-?\d+)', deletion)
    if not mut_sites:
        raise ValueError(f"cannot match deletion {deletion}")
    mut_list.append([int(mut_sites.group('start')), int(mut_sites.group('end'))])
```

4. Do you need the `key=` argument in `sort`? I thought it by default sorted by first tuple element?

5. I don't understand why you create the `merged` list at all. Why don't you just assign `previous = mut_list[0]` and then start the loop with `for current in mut_list[: 1]:`?

6. More generally, the code doesn't work right now except in the special case the deletions to be merged are the first two deletions in the sequence. The reason is that the convoluted structure of the above loop masks the fact that you are always comparing later deletions to just the first one. Try running this `merge_dels('del1390to1701 del5to7 del1702to1909 del1920to1930 G885T G85T')`, and you'll see it gives the wrong answer. It may be worth outlining the desired algorithm to make sure to avoid problems like this.

**Comment by Bernadetadad** [comment]
@jbloom I've  corrected the `merge_dels` function, it now merges as expected:
```
merge_dels('del12to15 del16to20 del21to30 del210to300 del1702to1909 del1910to1930 G885T G85T')
['G85T', 'G885T', 'del12to30', 'del210to300', 'del1702to1930']
```

**Review by jbloom — APPROVED** [review]

**Comment by jbloom** [comment]
@Bernadetadad, nice job on this. I pushed another few commits to (1) fix the flake-ing errors, (2) streamline the code.

I then approved. Take a look, and if it seems good to you then merge.

**Comment by Bernadetadad** [comment]
@jbloom sorry, I noticed that this is going to throw an error if no deletions are present, so I just added command to return the current mutation string if no deletions are found.

**Comment by jbloom** [comment]
@Bernadetadad, I made a few more changes to clarify in docs this is returning a **string**, make the doctest show that, and sort the string. If this looks good to you and works in your code, then merge the pull request and I'll make a new version.

**Review by Bernadetadad — COMMENTED** [review]
Looks good.

**Pull request merged**
