### PR TITLE
update reportfile parsing for ccs v6

### PR DESCRIPTION
**Pull request by andrewwbutler**
The latest version of `pbccs` produces a slightly modified version of the reportfile that is incompatible with the current parsing code (example of new format added to `report_to_stats` docs) . The PR makes the following changes 

## Adds
- `_report_to_stats_v6` - function for parsing the v6 version of the reportfile
- `_reportfile_version_check` - function to check the reportfile against a version specific pattern
- `_reportfile_to_dict` - function to read in the reportfile and convert it to a python dictionary
- `_reportdict_to_df` - function to convert the reportfile dictionary into a pandas DataFrame

## Modifies
- `_report_to_stats_v5` and `_report_to_stats_v4` to make use of new parsing functions.

## Rationale

I had initially tried to just copy and modify `_report_to_stats_v5` to make `_report_to_stats_v6` but the regex parsing strategy didn't extend well to the new format if we want to capture metrics after "Additional passing metrics" as you run into catastrophic backtracking issues. I thought it might be easier just to parse the colon separated values into a dictionary rather than get try and get fancier with the regex.

### CODE REVIEW

**Review by jbloom — CHANGES_REQUESTED** [review]
@andrewwbutler, can you fix the test failures [here](https://app.travis-ci.com/github/jbloomlab/alignparse/builds/255064393).

Looks like one is just some `flake8-bugbear` failure.

I think the next error may be because of indentation in the displayed data frame. Not sure why: either pandas changed how it indents output or something more subtle. You can possibly just change indentation in doctest, or there is an ignore whitespace option to doctest.

The other ones all appear to be how `nbval` is evaluating the output of the `plotnine` plots, which must have changed with `plotnine` version. Since all we are really testing on those cells is if the output is generated w/o error, you can probably just add `#NBVAL_IGNORE_OUTPUT to the beginning of each of those cells.

**Comment by andrewwbutler** [comment]
@jbloom I fixed the doctest and notebook tests. However the flake8 error is a bit more complicated (maybe triggered by a flake8 update as it's coming from a file I didn't modify in this PR). Basically, in the `align_and_parse` function, there is an ExitStack callback defined that removes certain files that are created in the case where an error occurs. This cleanup function (`delete_files_on_err`) uses the for loop index variable `t`, which is what flake8 is complaining about. However, because of how these decorators work in python, it seems that the callback function can't take parameters so I don't think just adding `t` to the `delete_files_on_err` function definition will work. Any thoughts on the best solution here?

**Comment by jbloom** [comment]
@andrewwbutler, code you did not modify is still failing on the new `flake8-bugbear` checks (you can see if you look at the Travis CI above).

To fix, change these lines: https://github.com/jbloomlab/alignparse/blob/master/alignparse/targets.py#L979-L981

To read
```
if os.path.isfile(aligned[t]):
    os.remove(aligned[t])
if os.path.isfile(filtered[t]):
    os.remove(filtered[t])
```

The problem is that it can cause problems to have loops going over looped variables, so this will fix that bugbear.

**Comment by andrewwbutler** [comment]
@jbloom, unfortunately that doesn't solve the issue (changing those lines and rerunning `flake8` results in the same error `B023`). From the `flake8-bugbear` docs:
> B023: Functions defined inside a loop must not use variables redefined in the loop, because [late-binding closures are a classic gotcha](https://docs.python-guide.org/writing/gotchas/#late-binding-closures).

The problem appears to caused by trying to use the loop index variable `t` within a function defined in the loop. One option that seems to fix the `flake8-bugbear` error would be to abstract everything in the `with` chunk into a separate function with `t` as one of its parameters. Maybe not the most elegant solution though and I'm not sure if it actually prevents what `flake8` is concerned about (just might be a way of hiding it from `flake8`).

**Comment by jbloom** [comment]
Sorry, this is annoying. It looks like you can also add arguments to `stack.callback`. Can you just make `t` an argument of that function? That should fix things, right? (Maybe this is what you are suggesting.)

**Comment by andrewwbutler** [comment]
@jbloom, couldn't quite figure out how to make it work while still using the decorator pattern but this should still do what we want and at least gets rids of the `flake` error.

**Review by jbloom — APPROVED** [review]

**Pull request merged**
