### PR TITLE
Review edits

### PR DESCRIPTION
**Pull request by khdusenbury**
Fixed bug in `ccs.py` script. I'm not sure why we started having a bug in how we were querying the ccs summaries data frames, but commit 5c902ab should fix the issue.

Incorporated reviewer edits (thank you @bede and @afrubin for your reviews!). 

@jbloom Some of the text edits sound a bit clunky, so please provide suggestions and/or edit as you see fit. Thanks!

### CODE REVIEW

**Comment by khdusenbury** [comment]
@jbloom Good point about the separate pull requests. I will be sure to do that moving forward. 

As for the `ccs` module breaking. I'm not sure why it started breaking, but if I run the `test_ccs_summaries.ipynb` notebook with the old code (currently in `master`), the `alignparse.ccs.Summaries(df)` command gives the error:

> TypeError:` 'Series' objects are mutable, thus they cannot be hashed

I tracked this error back to the way we were using `.query` in the original code. I'm not sure why this suddenly started breaking, but with the changes I made, this code now runs fine.

**Comment by jbloom** [comment]
@khdusenbury: Where was the old test failing? On the server, or on Travis?

**Comment by khdusenbury** [comment]
@jbloom The old test was failing on the server. I noticed it when I was updating the LASV example to use a gzipped FASTQ as I couldn't create any `Summaries` objects. Then I noticed all the notebooks making `Summaries` objects were failing when I ran `pytest`

Just incremented the version. Thanks for looking through everything.

**Comment by jbloom** [comment]
@khdusenbury: I just merged the pull request and am putting the updated version on PyPI after tagging it.

Do you want to close the GitHub issues referencing the relevant commits / pull requests? Then let me know if you are able to take care of the rest of the *JOSS* revision steps or need help from me at all.

**Pull request merged**
