### PR TITLE
Filter supplementary alignments

### PR DESCRIPTION
**Pull request by khdusenbury**
Do not parse supplementary alignments.

Currently, this is not an argument, but is simply hard-coded in. If you think we should make it a boolean option to `parse_alignments` and `align_and_parse`, let me know. 

This pull request updates the `targets.py`, the recA and VEP notebooks, and the vep example files.

### CODE REVIEW

**Comment by khdusenbury** [comment]
There seem to be some errors with things being printed in the jupyter notebooks. The notebooks pass when I run `pytest` from my command line, so I'm not entirely sure how to get the Travis build to pass. Perhaps we can take a look tomorrow?

**Comment by jbloom** [comment]
@khdusenbury: Commit a22ea5b should fix one of the causes of the tests failing by better sanitizing the HTML rendering of data frames. See that detailed commit message for explanation.

I'm still not sure where the `.DS_Store` file is coming from that is still causing a test fail; I'll look at this more shortly.

**Comment by jbloom** [comment]
@khdusenbury: I fixed the other failing test in commit 3d8fe8a. The commit and its message should be self-explanatory.

**Comment by khdusenbury** [comment]
I agree with making the arguments to `parse_alignment` keyword arguments, but I'm struggling figuring out how to handle the keyword arguments when running `parse_alignment` within `align_and_parse` using the `map_func` structure. Perhaps you could show me how to do this?

**Comment by jbloom** [comment]
@khdusenbury: Whoops, you can't do it with `map_func`. I had forgotten about that. I guess just make it order-dependent arguments. In this case, new arguments should always be added to the end of the list, updating the `map_func` arguments appropriately to match that order. Does this make sense?

**Comment by khdusenbury** [comment]
Makes sense. Will do that now.

**Comment by khdusenbury** [comment]
I think this should be ready to merge if it looks good on your end.

**Pull request merged**
